version: 2
jobs:
    build:
      docker:
        - image: eu.gcr.io/pi-ostelco-prod/helm-builder:2.11.0
      steps:
        - checkout
        - run:
            name: initialize, build charts and push them to the helm charts repo on GCS
            command: |
              chmod +x .circleci/package.sh
              .circleci/package.sh
workflows:
  version: 2
  package-and-push:
    jobs:
      - build:
          filters:
            branches:
              only: master


