{{- if .Values.certs.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "prime.fullname" . }}-api-crt
spec:
  secretName: api-tls
  dnsNames:
  {{- range .Values.certs.apiDns }}
  - {{ . }}
  {{- end }}
  issuerRef:
    name: {{ .Values.certs.issuer }}
    kind: ClusterIssuer
  acme:
    config:
    - dns01:
        provider: {{ .Values.certs.dnsProvider }}
      domains:
      {{- range .Values.certs.apiDns }}
      - {{ . }}
      {{- end }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "prime.fullname" . }}-ocs-crt
spec:
  secretName: ocs-tls
  dnsNames:
  {{- range .Values.certs.ocsDns }}
  - {{ . }}
  {{- end }}
  issuerRef:
    name: {{ .Values.certs.issuer }}
    kind: ClusterIssuer
  acme:
    config:
    - dns01:
        provider: {{ .Values.certs.dnsProvider }}
      domains:
      {{- range .Values.certs.ocsDns }}
      - {{ . }}
      {{- end }} 
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "prime.fullname" . }}-metrics-crt
spec:
  secretName: metrics-tls
  dnsNames:
  {{- range .Values.certs.metricsDns }}
  - {{ . }}
  {{- end }}
  issuerRef:
    name: {{ .Values.certs.issuer }}
    kind: ClusterIssuer
  acme:
    config:
    - dns01:
        provider: {{ .Values.certs.dnsProvider }}
      domains:
      {{- range .Values.certs.metricsDns }}
      - {{ . }}
      {{- end }}      
{{- end -}}
