{{- if .Values.cronjobs.extractor.enabled  }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bq-metrics-extractor
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:  bq-metrics-extractor
            image: {{ .Values.cronjobs.extractor.image }}:{{ .Values.cronjobs.extractor.tag }}
            imagePullPolicy: Always
            env:
            - name: DATASET_PROJECT
              value: {{ .Values.cronjobs.extractor.dataset_project | default "pi-ostelco-dev" }}
            - name: ANALYTICS_DATASET
              valueFrom:
                secretKeyRef:
                  name: analytics-secrets
                  key: analyticsDatasetName
          restartPolicy: Never
{{- end }}
