{{- if .Values.podAutoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "prime.name" $ }}
    chart: {{ template "prime.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    tag: {{ $.Values.prime.tag }}
  name: {{ template "prime.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "prime.fullname" . }}
  minReplicas: {{ .Values.podAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.podAutoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.podAutoscaling.metrics | nindent 4 }}
{{- end }}