{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app: {{ template "prime.name" $ }}
    chart: {{ template "prime.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    tag: {{ $.Values.prime.tag }}
  {{- if .host }}  
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  {{ $.Release.Name }}_{{ .name }}_mapping
      host:  {{ $.Values.dnsPrefix }}{{ .host }}{{ $.Values.dnsSuffix }}
      prefix: /
      {{- if .grpcOrHttp2 }}
      grpc: True
      {{- end }}
      service: {{ $.Release.Name }}-{{ .name }}.{{ $.Release.Namespace }} 
      {{- with .ambassadorMappingOptions }}
{{ toYaml . | indent 6 }}      
      {{- end }} 
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: {{ $.Release.Name }}_{{ .name }}_context
      hosts:
      - {{ $.Values.dnsPrefix }}{{ .host }}{{ $.Values.dnsSuffix }}
      secret: {{ $.Values.certs.tlsSecretName }}.{{ $.Release.Namespace }}
      {{- if .clientCert }}
      ca_secret: {{ .caCert }}
      cert_required: True
      {{- end }}
      {{- if .grpcOrHttp2 }}
      alpn_protocols: h2
      {{- end }}
  {{- end }}    
spec:
  type: {{ .type }}
  {{- if and .loadBalancerIP (eq .type "LoadBalancer") }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }} 
      protocol: TCP
      name: {{ .portName }}
  selector:
    app: {{ template "prime.name" $ }}
    release: {{ $.Release.Name }}
    tier: backend
---
{{- end }}

# canary service
{{- if and .Values.canary .Values.services.api }}
{{- with .Values.services.api }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-canary
  labels:
    app: {{ template "prime.name" $ }}
    chart: {{ template "prime.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    track: canary
    tag: {{ $.Values.canary.tag }}
  annotations:
    getambassador.io/config: |
      --- 
      apiVersion: ambassador/v1
      kind: Mapping
      name: {{ $.Release.Name }}_{{ .name }}_canary_mapping
      service: {{ $.Release.Name }}-{{ .name }}-canary.{{ $.Release.Namespace }}
      prefix: /
      {{- if .grpcOrHttp2 }}
      grpc: True
      {{- end }}
      {{- if $.Values.canary.headers }}
      headers:
        {{- range $k,$v := $.Values.canary.headers }}
        {{ $k }}: {{ $v }}
        {{- end }}
      {{- end }}  
      {{- if not $.Values.canary.headers }}
      weight: {{ $.Values.canary.weight }}  
      {{- end }}
      host: {{ $.Values.dnsPrefix }}{{ .host }}{{ $.Values.dnsSuffix }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }} 
      protocol: TCP
      name: {{.portName }}
  selector:
    app: {{ template "prime.name" $ }}-canary
    release: {{ $.Release.Name }}
    tier: backend
    track: canary
{{- end }}
{{- end }}