{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app: {{ template "prime.name" $ }}
    chart: {{ template "prime.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: {{ .type }}
  {{- if .loadBalancerIP }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }} 
      protocol: TCP
      name: {{.portName }}
  selector:
    app: {{ template "prime.name" $ }}
    release: {{ $.Release.Name }}
    tier: backend
---
{{- end }}