apiVersion: v1
kind: Service
metadata:
  name: {{ include "hss-adapter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hss-adapter.name" . }}
    helm.sh/chart: {{ include "hss-adapter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{ range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name:  {{ .name }}
  {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "hss-adapter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
