apiVersion: batch/v1
kind: Job
metadata:
  name: echo-post-install
  labels:
{{ include "echoserver.labels" . | indent 4 }}
    generator: helm
    time: {{ .Release.Time.Seconds }}
    version: {{ .Chart.Version }}
  annotations:
    "helm.sh/hook": "post-install"
template:
  metadata:
    name: post-install-pod
  spec:
    containers:
      # [start of curl container]
    - name: echo
      image: pstauffer/curl:latest
      imagePullPolicy: IfNotPresent

      command: ["/bin/sh", "-c"]
      args:
      - |
        sleep {{ .Values.post_install.delay }}
        # make the message and link below dynamic. The link format is: <service-name>.<namespace>.svc.cluster.local:<service-port>/content
        # append a random alpha numeric string of 5 characters to end of the message.
        curl -F "message=POST INSTALLING MESSAGE SENT BY '${HOSTNAME}'----> {{ .Values.post_install.message }}" {{ template "echoserver.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}/content
    restartPolicy: OnFailure
# [end of curl container]